<header id="header-area">
	
	<figure><img src="http://students.thenet.ca/cnovakov/images/student_logo.jpg" alt="JEMTC Logo" ></figure>
	 
	 <section class="section-style-horizontal">
		<ul>
			<li><a href="http://my.bcit.ca/">my.bcit</a></li>
			<li><a href="http://www.bcit.ca/">bcit</a></li>
			<li><a href="http://www.computing.bcit.ca/">bcit: computing</a></li>
			<li><a href="http://www.alistair.com/">alistair.com</a></li>
			<li>search</li>
			<li><form id="loc-search" method="post"> 
				<input autocomplete="on" name="keywords" value="Richmond, BC" class="" type="text">	
				<INPUT type="image" src="images/searchicon.jpg" value="" style="background-color:#b5bfc1;color:red">				
			</form></li>
		</ul>
	</section>
	
	</header>
	
