    <header>	
    	<figure><img src="http://students.thenet.ca/cnovakov/images/student_logo.jpg" alt="JEMTC Logo" ></figure>
    	<section class="section-style-horizontal">
    		<ul>
    			<li>Search</li>
    			<li>
                    <form id="loc-search" method="post"> 
    				    <input autocomplete="on" name="keywords" value="Richmond, BC" class="" type="text">	
    				    <input type="image" src="images/searchicon.jpg" value="" style="background-color:#b5bfc1;color:red">				
    			    </form>
                </li>
    		</ul>
    	</section>	
    </header>	