    <header>	
    	<figure><img src="images/student_logo.jpg" alt="Comp1950 Student Page" ></figure>
    	<section class="section-style-horizontal">
    		<ul>
    			<li>Search</li>
    			<li>
                    <form id="loc-search" method="post"> 
    				    <input autocomplete="on" name="keywords" value="Richmond, BC" class="" type="text">	
    				    <input type="image" src="http://teams.thenet.ca/jemtc/images/searchicon.jpg" alt="search magnifier">				
    			    </form>
                </li>
    		</ul>
    	</section>	
    </header>	
