<footer id="footer-area">
			<nav>
				<ul class="footer-nav">			
					<li><a href="http://teams.thenet.ca/jemtc/">Home</a></li>
					<li><a href="http://teams.thenet.ca/jemtc/JEMTC1950.shtml" target="_blank">Proto-Site</a></li>
					<li><a href="http://teams.thenet.ca/jemtc/drafts/Wireframes/jemtc-wireframes.pdf">Wireframes</a></li>
					<li><a href="http://teams.thenet.ca/jemtc/drafts/sitemap.pdf">Sitemap</a></li>
					<li><a href="http://teams.thenet.ca/jemtc/rationale.shtml">Rationale-Docs</a></li>
				</ul>
			</nav>
		</footer>