	<div id="left-area">		
		<nav>			
			<ul class="nav">				
			<li><a href="proto-home.html">Home</a></li>
			<li><a href="#">Course Outline</a></li>
			<li><h4>Lectures</h4></li>
			<li><a href="proto-lecture.html">Lecture 1</a></li>
			<li><a href="#">Lecture 2</a></li>
			<li><a href="#">Lecture 3</a></li>
			<li><a href="#">Lecture 4</a></li>
			<li><a href="#">Lecture 5</a></li>
			<li><a href="#">Lecture 6</a></li>
			<li><a href="#">Lecture 7</a></li>
			<li><a href="#">Lecture 8</a></li>
			<li><a href="#">Lecture 9</a></li>
			<li><a href="#">Lecture 10</a></li>
			<br />
			<li><a href="#">Homework</a></li>
			<li><a href="jemtc.tumblr.com">Blog</a></li>
			</ul>
		</nav>	
	</div>
