	<div id="left-area">		
		<nav>			
			<ul class="nav">				
			<li><a href="http://teams.thenet.ca/jemtc/JEMTC1950.shtml">Home</a></li>
			<li><a href="http://www.bcit.ca/study/courses/comp1950">Course Outline</a></li>
			<li><h4>Lectures</h4></li>
			<li><a href="http://teams.thenet.ca/jemtc/lecture1.shtml">Lecture 1</a></li>
			<li><a href="#">Lecture 2</a></li>
			<li><a href="#">Lecture 3</a></li>
			<li><a href="#">Lecture 4</a></li>
			<li><a href="#">Lecture 5</a></li>
			<li><a href="#">Lecture 6</a></li>
			<li><a href="#">Lecture 7</a></li>
			<li><a href="#">Lecture 8</a></li>
			<li><a href="#">Lecture 9</a></li>
			<li><a href="#">Lecture 10</a></li>
			<li><a href="#">Homework</a></li>
			<li><a href="http://jemtc.tumblr.com/">Blog</a></li>
			</ul>
		</nav>	
	</div>
