<div id="left-area">	
		<nav>			
			<ul class="nav shadow">				
				<li><a href="http://teams.thenet.ca/jemtc/">Home</a></li>
				<li><a href="JEMTC1950.shtml" target="_blank">Proto-Site</a></li>
				<li><a href="/">Wireframes</a></li>
				<li><a href="/">Sitemap</a></li>
				<li><a href="/">Rationale-Docs</a></li>
			</ul>
		</nav>
		
		<section class="section-style shadow">
					<h6 class="heading-format">CONTACT</h6>	
					<a href="mailto:alistaircalder@my.bcit.ca">Alistair Calder</a>
		</section>
		<section class="section-style shadow">
					<h6 class="heading-format">ASSOCIATED LINKS</h6>
					<a href="http://my.bcit.ca/">my.bcit</a><br>
					<a href="http://www.bcit.ca/">bcit</a><br>
					<a href="http://www.computing.bcit.ca/">bcit: computing</a>
					<a href="http://www.alistair.com/">alistair.com</a>
		</section>
		<section class="section-style shadow">
			<h6 class="heading-format">CONNECT WITH US</h6>
			<a href="http://facebook.com"><img src="http://students.thenet.ca/tremany/week8/images/fbicon.png" alt="facebook icon" width="20" height="20"></a>&nbsp;<a href="http://twitter.com"><img src="http://students.thenet.ca/tremany/week8/images/twittericon.png"  alt="twitter icon" width="20" height="20"></a>&nbsp;<a href="http://youtube.com"><img src="http://students.thenet.ca/tremany/week8/images/youtube.png"  alt="youtube icon" width="20" height="20"></a>
		</section>
		<section class="section-style shadow">
					<h6 class="heading-format">VALIDATION LINKS</h6>	
			<a href="http://validator.w3.org/check?uri=referer">HTML 5</a><BR>
			<a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a>

		</section>		
	</div>