	<div id="left-area">	
		<section class="section-style">
			<h6 class="heading-format">CONNECT WITH US</h6>
			<a href="http://facebook.com"><img src="http://students.thenet.ca/tremany/week8/images/fbicon.png" alt="facebook icon" width="20" height="20"></a>&nbsp;<a href="http://twitter.com"><img src="http://students.thenet.ca/tremany/week8/images/twittericon.png"  alt="twitter icon" width="20" height="20"></a>&nbsp;<a href="http://youtube.com"><img src="http://students.thenet.ca/tremany/week8/images/youtube.png"  alt="youtube icon" width="20" height="20"></a>
		</section>	
		<nav>			
			<ul class="nav">				
				<li><a href="proto-home.html">Home</a></li>
			<li><a href="proto-lecture.html">Lecture 1</a></li>
			<li><a href="jemtc.tumblr.com">Blog</a></li>
			<li><a href="homework.html">Homework</a></li>
			<li><a href="Alumni.html">Alumni</a></li>
			</ul>
		</nav>
		<section class="section-style">
					<h6 class="heading-format">CONTACT</h6>	
					<p><a href="mailto:alistaircalder@my.bcit.ca">Alistair Calder</a></p>
		</section>
	</div>