<div id="right-area">
		<aside>
			<section class="section-style">
				<form id="loc-search" method="post"> 
				<h6 class="heading-format">SEARCH</h6>	
					<input autocomplete="on" name="keywords" value="Richmond, BC" class="" type="text">	<INPUT type="image" src="http://students.thenet.ca/tremany/week8/images/searchicon.jpg" value="" style="background-color:#b5bfc1;color:red">				
			</form>
			</section>
			<section class="section-style">
				<h6 class="heading-format">HELPFUL LINKS</h6></p>	
				<ul class="nav">
					<li>
						<a href="http://www.bcit.ca/study/courses/comp1950">Course Outline</a>
						<div></div>
					</li>
					<li>
						<a href="#">Sites</a>
						<div></div>
					</li>	
					<li>
						<a href="#">Books</a>
						<div></div>
					</li>
				</ul>					
			</section>
			<section class="section-style">
					<h6 class="heading-format">ASSOCIATED LINKS</h6>
					<p><a href="http://my.bcit.ca/">my.bcit</a><br>
					<a href="http://www.bcit.ca/">bcit</a><br>
					<a href="http://www.computing.bcit.ca/">bcit: computing</a></br>
					<a href="http://www.alistair.com/">alistair.com</a></p>
			</section>
			<section class="section-style">
			<h6 class="heading-format">CONNECT WITH US</h6>
			<a href="http://facebook.com"><img src="images/fbicon.png" alt="facebook icon" width="20" height="20"></a>&nbsp;<a href="http://twitter.com"><img src="images/twittericon.png"  alt="twitter icon" width="20" height="20"></a>&nbsp;<a href="http://youtube.com"><img src="images/youtube.png"  alt="youtube icon" width="20" height="20"></a>
		</section>	
		<section class="section-style">
					<h6 class="heading-format">CONTACT</h6>	
					<p><a href="mailto:alistaircalder@my.bcit.ca">Alistair Calder</a></p>
		</section>
		</aside>
	</div>