<!-- Right nav for prototype -->

    <div id="right-area">
		<aside>
			<ul class="nav">
				<li><a href="http://teams.thenet.ca/jemtc/">Contact</a></li>
				<li><h4>Associated Links</h4></li>	
				<li><a href="https://my.bcit.ca/cp/home/displaylogin" target="_blank">my.bcit</a></li>
				<li><a href="http://www.bcit.ca/" target="_blank">bcit</a></li>
				<li><a href="http://www.bcit.ca/study/programs/cst" target="_blank">bcit: computing</a></li>
				<li><a href="http://www.alistair.com/" target="_blank">alistair.com</a></li>
				<li><h4>Validation</h4></li>
				<li><a href="http://validator.w3.org/check?uri=referer">HTML 5</a></li>
				<li><a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a></li>
			</ul>					
		</aside>
	</div>	
